name: Test

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [master]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true
          activate-environment: true
      - run: uv sync --dev --extra litellm --prerelease=allow
      - run: poe lint
      - run: poe format-check
      - run: poe typecheck
      - run: poe test
